
services:
  postgres:
    image: postgres:16-alpine
    container_name: tg_training_log_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  app:
    build:
      dockerfile: Dockerfile
    container_name: tg_training_log_app
    env_file: .env
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      # - ./src:/app/src
      - ./logs:/app/logs
      - ./tgtraining-69d93acc8e17.json:/app/tgtraining-69d93acc8e17.json:ro

volumes:
  postgres_data:

